# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18o_Qfadxjz2LnsvaEqRjduhSwhaiyvnm
"""

!pip install -q cohere pypdf

import cohere

# 1. Configurar la API Key de Cohere de forma segura mediante los Secrets de Streamlit
try:
    COHERE_API_KEY = st.secrets["COHERE_API_KEY"]
except:
    st.error("❌ Falta configurar la COHERE_API_KEY en los Secrets de Streamlit Cloud.")
    st.stop()
    
co = cohere.Client(COHERE_API_KEY)

# Le pedimos a Cohere la lista de modelos disponibles para Chat
print("Tus modelos disponibles para usar son:")
for modelo in co.models.list().models:
    if 'chat' in modelo.endpoints:
        print(f"- {modelo.name}")

import os
from pypdf import PdfReader
import cohere

# 1. Configura tu API Key de Cohere aquí

co = cohere.Client(COHERE_API_KEY)

# 2. Leer el PDF de la cafetería
lector = PdfReader("informacion_cafeteria.pdf")
contenido_pdf = ""
for pagina in lector.pages:
    contenido_pdf += pagina.extract_text() + "\n"

# 3. Función del Agente usando el modelo verificado de tu lista
def preguntar_al_agente(pregunta):
    instrucciones = (
        "Eres el asistente virtual de 'Café Estelar'. Tu deber es responder preguntas de los clientes "
        "basándote únicamente en la información proporcionada a continuación.\n\n"
        f"Información de la Cafetería:\n{contenido_pdf}\n\n"
        "Si la respuesta no está en el texto, di amablemente que no cuentas con esa información."
    )

    # Usamos el modelo confirmado de tu lista
    respuesta = co.chat(
        model="command-r-08-2024",
        message=pregunta,
        preamble=instrucciones
    )

    print(f"Pregunta: {pregunta}")
    print(f"Respuesta: {respuesta.text}\n")

# --- ¡PROBEMOS TU AGENTE! ---
preguntar_al_agente("¿Tienen internet y cuál es la contraseña?")

import os
from pypdf import PdfReader
import cohere

# 1. Configura tu API Key de Cohere aquí
COHERE_API_KEY = "TU_API_KEY_DE_COHERE_AQUI"
co = cohere.Client(COHERE_API_KEY)

# 2. Leer el PDF de la cafetería
lector = PdfReader("informacion_cafeteria.pdf")
contenido_pdf = ""
for pagina in lector.pages:
    contenido_pdf += pagina.extract_text() + "\n"

# 3. Instrucciones del sistema
instrucciones = (
    "Eres el asistente virtual de 'Café Estelar'. Tu deber es responder preguntas de los clientes "
    "basándote únicamente en la información proporcionada a continuación.\n\n"
    f"Información de la Cafetería:\n{contenido_pdf}\n\n"
    "Si la respuesta no está en el texto, di amablemente que no cuentas con esa información."
)

# --- BUCLE DE CHAT CON MEMORIA ---
print("¡Chat con Memoria de Café Estelar iniciado! (Escribe 'salir' para terminar)\n")

# Creamos la lista vacía para almacenar el historial de esta sesión
historial = []

while True:
    pregunta_usuario = input("Tú: ")

    if pregunta_usuario.lower() in ["salir", "exit", "quit", "adiós", "adios"]:
        print("\nAgente: ¡Gracias por visitar Café Estelar! Que tengas un gran día.")
        break

    if not pregunta_usuario.strip():
        continue

    # Enviamos el 'historial' actual en la petición
    respuesta = co.chat(
        model="command-r-08-2024",
        message=pregunta_usuario,
        preamble=instrucciones,
        chat_history=historial
    )

    print(f"Agente: {respuesta.text}\n")

    # Guardamos este turno en el historial para la siguiente pregunta
    historial.append({"role": "USER", "message": pregunta_usuario})
    historial.append({"role": "CHATBOT", "message": respuesta.text})

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# streamlit>=1.30.0
# cohere>=5.0.0
# pypdf>=4.0.0
